{
 "title": "Nginx",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_requests{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency Q0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Q0.5"
    }
   ]
  },
  {
   "title": "Latency Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Q0.95"
    }
   ]
  },
  {
   "title": "Latency Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Q0.99"
    }
   ]
  },
  {
   "title": "Latency Qmax",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Qmax"
    }
   ]
  }
 ]
}
{
 "title": "User service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"user-service\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container='user-service'})/1024/1024",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Count of requests per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(user_service_request_count[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (increase(user_service_request_count{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Latency Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Q0.5",
   "type": "timeseries",
   "description": "Response time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Qmax",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  }
 ]
}
{
 "title": "Postgresql",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "172.17.0.13:9187" },
   { "name": "db", "query": "users_db" }
  ]
 },
 "panels": [
  {
   "title": "Backends connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{instance='$instance',datname='$db'}"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * avg(rate(pg_stat_database_blks_hit{instance='$instance',datname='$db'}[5m]) / (rate(pg_stat_database_blks_hit{instance='$instance',datname='$db'}[5m]) + rate(pg_stat_database_blks_read{instance='$instance',datname='$db'}[5m])))",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Fetched / Returned Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(pg_stat_database_tup_fetched{instance='$instance',datname='$db'}[5m]) / rate(pg_stat_database_tup_returned{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance='$instance',datname='$db'}"
    }
   ]
  },
  {
   "title": "Locks by Mode ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_locks_count{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Query Locks Errors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts_confl_lock{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "lock timeouts"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_deadlock{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "Connections by state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_activity_count{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Max Duration by State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(pg_stat_activity_max_tx_duration{instance='$instance',datname='$db'}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Read Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{instance='$instance',datname='$db'}[5m]) / rate(pg_stat_database_blks_read{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "Commit"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "Fetched / Returned Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Heap Only Tuple Updates Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum by (datname)(rate(pg_stat_user_tables_n_tup_hot_upd{instance='$instance',datname='$db'}[5m])) / (sum by (datname)(rate(pg_stat_user_tables_n_tup_hot_upd{instance='$instance',datname='$db'}[5m])) + sum by (datname)(rate(pg_stat_database_tup_updated{instance='$instance',datname='$db'}[5m])))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "IOPS by Function",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "update"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{instance='$instance',datname='$db'}[5m]) ",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Data Written to Temporary Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{instance='$instance',datname='$db'}[5m])",
     "legendFormat": "Data Written"
    }
   ]
  },
  {
   "title": "Index vs Sequential Scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(pg_stat_user_tables_idx_scan{instance='$instance',datname='$db'})",
     "legendFormat": "index scan"
    },
    {
     "expr": "sum by (datname)(pg_stat_user_tables_seq_scan{instance='$instance',datname='$db'})",
     "legendFormat": "seq scan"
    }
   ]
  }
 ]
}