/*
 * User Service
 *
 * This is simple client API
 *
 * API version: 1.0.0
 * Contact: schetinnikov@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
