{
 "title": "Nginx",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_requests{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency Q0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Q0.5"
    }
   ]
  },
  {
   "title": "Latency Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Q0.95"
    }
   ]
  },
  {
   "title": "Latency Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Q0.99"
    }
   ]
  },
  {
   "title": "Latency Qmax",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Qmax"
    }
   ]
  }
 ]
}