{
 "title": "User service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"user-service\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container='user-service'})/1024/1024",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Count of requests per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(user_service_request_count[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (increase(user_service_request_count{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Latency Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Q0.5",
   "type": "timeseries",
   "description": "Response time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Qmax",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, route, method)(rate(user_service_request_latency_seconds_bucket[1m]))) * 1000"
    }
   ]
  }
 ]
}